import Head from "next/head";
import * as S from "../src/components/commons/styles/index.styles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Wrapper>
        <S.CardBox>
          {[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0].map((el) => (
            <S.Card key={el}>카드1</S.Card>
          ))}
        </S.CardBox>
      </S.Wrapper>
    </>
  );
}
