import Head from "next/head";
import * as S from "../src/components/commons/styles/index.styles";
import Card from "../src/components/units/index/index.card";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stage Pick</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <S.Wrapper>
        <S.CardBox>
          {[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0].map((el) => (
            <Card
              title="드라큘라"
              time="11월 11일 오후 4시"
              description="국무회의는 정부의 권한에 속하는 중요한 정책을 심의한다."
              cast="박효신, 김준수"
              key={el}
            />
          ))}
        </S.CardBox>
      </S.Wrapper>
    </>
  );
}
